FROM node:13

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn

# Coying the app
COPY . .

ENV API_URL=${API_URL}
ENV RECAPTCHA_KEY=${RECAPTCHA_KEY}

# Running the app
CMD [ "yarn", "dev" ]
